### ISSUE TITLE
node builds don't actually run in nodeBuild.feature

### ISSUE THREAD

**Issue by claymccoy** [atomist/sdm-smoke-test#11]
I don't think nodeBuild.feature ever fully worked. It first tests for a successful build, and then creates errors with an editor and expects the build to fail. But a real build is never run. It will just echo text, even when the code won't compile.
```
 "scripts": {
    "start": "node server.js",
    "build": "echo builded!"
  }
```

**Comment by jessitron** [comment]
are those scripts in our seed? ... where is that package.json coming from?

**Comment by claymccoy** [comment]
Used a new node project with a legit build.
Rather than https://github.com/spring-team/minimal-node-seed, we use https://github.com/spring-team/buildable-node-seed.
